# === Baseline config: EURUSD 2023 ===
FAST_MODE: true
LOG_TRADES: true
PROGRESS_EVERY: 50000

DATA_CSV_PATH: data/clean/EURUSD/2023/EURUSD_1y_2023_clean.csv
ACCOUNT_START: 25000.0
RISK_PER_TRADE: 0.005
MACD_EPS: 1.0e-6

ATR_MULT_SL: 1.5
ATR_MULT_TP: 2.1
MAX_BARS_HOLD: 240

RSI_BUY_MAX: 33.0
RSI_SELL_MIN: 67.0
RSI_WINDOW_AHEAD: 6

ATR_BAND_LOOKBACK: 1000
ATR_P_LOW: 0.28
ATR_P_HIGH: 0.90
ATR_MIN_WARMUP: 200

EMA_TREND_RECENT: 6

USE_BREAKEVEN: true
BE_MULT: 0.90
BE_MIN_BARS_HELD: 15

USE_SESSION_FILTER: true
SESSION_START_HHMM: 600
SESSION_END_HHMM: 2100
TRADE_WEEKDAYS_ONLY: true

EXCLUDE_UTC_HOURS: [11, 12]
EXCLUDE_WEEKDAYS: []

DISABLE_LONG_COMBO: true
RSI_LONG_BAD_CUTOFF: 30.0

USE_APRIL_ATR_TIGHTENING: true
APRIL_ATR_P_LOW: 0.32

DYN_SL_ENABLE: false
ATR_PCNT_WIDE_SL_FROM: 0.70
ATR_MULT_SL_BASE: 1.5
ATR_MULT_SL_WIDE: 2.0

MAX_DAILY_DD: 0.038
MAX_TOTAL_DD: 0.07
