name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pyyaml

      - name: Run smoke tests (fast)
        run: pytest -q

      - name: (Optional) Run slow tests
        if: github.event_name == 'workflow_dispatch'
        run: pytest -q -m slow
