name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'   # enables pip cache automatically

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Run tests (fast + slow) with coverage
        run: |
          pytest -q --cov=src --cov-report=xml

      - name: Upload coverage xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      # Optional: if your tests write a trades CSV to runs/, upload it
      - name: Upload backtest outputs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backtest-outputs
          path: runs/
          if-no-files-found: ignore
